# NOTE: Games are configured using YAML: http://www.yaml.org
---

# Basic game configuration
#

title: Cloak of Darkness
width: 600
height: 600
image_height: 200
resizable: true

# Standard commands that should be included in the game
#

standard_commands:
- drop
- get
- go
- inventory
- look
- put
- quit
- read
- remove
- score
- wear

# Command abbreviations
#

command_abbreviations:
  n: "go north"
  s: "go south"
  e: "go east"
  w: "go west"
  u: "go up"
  d: "go down"

# Words that should be ignored during parsing
#

garbage_words:
- "the"
- "that"
- "this"
- "at"
- "to"

# Global synonyms
#

global_synonyms:
  using: "with"
  examine: "look"

# Scoring components
#

scoring:
  cloak_on_hook:
    points: 1

  message_read:
    points: 1

# What to display when game starts
#

startup_message: "Hurrying through the rainswept November night, you're glad to see the bright lights of the Opera House. It's surprising that there aren't more people about but, hey, what do you expect in a cheap demo game...?\n
  \n
  Cloak of Darkness\n
  A Basic IF Demonstration\n
  Written using Fashion Quest by Mike Cantelon (c) 2009\n
  \n"

# Logic that defines the initial state of game elements
#

setup_logic: |

  @game.state['trampling'] = 0

  # Define player

  player = @game.create(Player)
  player.location = 'foyer'
  @game.player = player

  # Define game props

  prop = @game.create(Prop, 'cloak')
  prop.name = 'velvet cloak'
  prop.aliases = ['handsome', 'dark', 'black', 'velvet', 'satin']
  prop.description = "A handsome cloak, of velvet trimmed with satin, and slightly spattered with raindrops. Its blackness is so deep that it almost seems to suck light from the room."
  prop.location = 'player'
  prop.traits = {
    'wearable' => true,
    'portable' => true
  }
  @game.props['cloak'] = prop

  hook = @game.create(Prop, 'hook')
  hook.name = 'small brass hook'
  hook.aliases = ['small', 'brass', 'peg']
  hook.description = 'Da coate hook!'
  hook.location = 'cloakroom'
  hook.traits = {
    'visible' => false,
    'portable' => false,
    'supports' => true,
    'supports_only' => ['cloak']
  }
  @game.props['hook'] = hook

  message = @game.create(Prop, 'message')
  message.location = 'bar'
  message.events = {
    'on_read' => "@game.set_score('message_read')\n\
      @game.over = true"
  }
  message.traits = {
    'visible' => false,
    'portable' => false,
    'text' => "The message, neatly marked in the sawdust, reads...\n
       *** You have won ***\n"
  }
  @game.props['message'] = message

  # Define game locations

  cloakroom = @game.create(Location, 'cloakroom')
  cloakroom.exits = {'east' => {'destination' => 'foyer'}}
  cloakroom.description = "The walls of this small room were clearly once lined with hooks, though now only one remains. The exit is a door to the east.\n"
  @game.locations['cloakroom'] = cloakroom

  bar = @game.create(Location, 'bar')
  bar.exits = {'north' => {'destination' => 'foyer'}}
  bar.description = "The bar, much rougher than you'd have guessed after the opulence of the foyer to the north, is completely empty. There seems to be some sort of message scrawled in the sawdust on the floor.\n"
  bar.dark = 'safe'
  @game.locations['bar'] = bar

  foyer = @game.create(Location, 'foyer')
  foyer.exits = {
    'north' => {'condition' =>
      "You've only just arrived, and besides, the weather outside seems to be getting worse.\n"
    },
    'south' => {'destination' => 'bar'},
    'west' => {'destination' => 'cloakroom'}
  }
  foyer.description = "You are standing in a spacious hall, splendidly decorated in red and gold, with glittering chandeliers overhead. The entrance from the street is to the north, and there are doorways south and west.\n"
  @game.locations['foyer'] = foyer

startup_logic: |

  # Define transitions

  @game.transitions = {
    "conditions"=> {
      ["@props['cloak'].location == 'player' || @props['cloak'].location == 'bar'"] \
        => ["bar_dark"],
      ["@props['cloak'].location != 'player' && @props['cloak'].location != 'bar'"] \
        => ["bar_light"],
      ["@props['hook'].traits['supporting'] && \
        @props['hook'].traits['supporting'].index('cloak')"] \
        => ["coat_hung"],
      ["!@props['hook'].traits['supporting'] || \
        !@props['hook'].traits['supporting'].index('cloak')"] \
        => ["coat_not_hung"]
    },
    "outcomes"=> {
      "bar_dark"  => "@locations['bar'].dark = 'safe'\n\
        ''\n",
      "bar_light" => "@locations['bar'].dark = false\n\
        ''\n",
      "coat_hung" => %!
        @props['hook'].description = "It's just a small brass hook, with a cloak on it, screwed to the wall."\n
        @game.set_score('cloak_on_hook')\n
      !,
      "coat_not_hung" => %!
        @props['hook'].description = "It's just a small brass hook, screwed to the wall."\n
        ''
      !
   }
  }

  # Command conditions

  def @game.drop_condition(game, prop)

    if prop.id == 'cloak' && game.player.location != 'cloakroom'
      {
        'message' => "This isn't the best place to leave a smart cloak lying around.\n",
        'success' => false
      }
    else
      {'success' => true}
    end
  end

  @cli.commands['drop'].condition = "@game.drop_condition(@game, prop)"

  def @game.go_condition(game, arg)

    if game.locations[game.player.location].dark and arg['direction'] != 'north'
      game.state['trampling'] = game.state['trampling'] + 2
      {
        'message' => "In the dark? You could easily disturb something!\n",
        'success' => false
      }
    else
      {'success' => true}
    end
  end

  @cli.commands['go'].condition = "@game.go_condition(@game, arg)"

  def @game.command_condition(game, command)

    allowed_commands = ['look', 'quit', 'go']

    if !allowed_commands.index(command.id) && game.locations[game.player.location].dark
      {
        'message' => "In the dark? You could easily disturb something!\n",
        'success' => false
      }
    else
      {'success' => true}
    end
  end

  @cli.command_condition = "@game.command_condition(@game, command)"

  # Start game by issueing "look" command
  @cli.issue_command('look', false)
