---
title: Cloak of Darkness
width: 600
height: 600
image_height: 200
resizable: true

startup_message: "Hurrying through the rainswept November night, you're glad to see the bright lights of the Opera House. It's surprising that there aren't more people about but, hey, what do you expect in a cheap demo game...?\n
  \n
  Cloak of Darkness\n
  A Basic IF Demonstration\n
  Written using Fashion Quest by Mike Cantelon (c) 2009\n
  \n"

startup_logic: |

  # add helper function to game to check for darkness and
  # return warning if it's dark
  def @game.command_check(command, prop, player, location, denial_message)

    message = false
    success = true

    if command == 'drop' && prop.id == 'cloak' && player.location != 'cloakroom'

      message = "This isn't the best place to leave a smart cloak lying around.\n"
      success = false

    else

      if (locations[player.location].dark)
        message = denial_message + "\n"
        success = false
      end
    end

    {'message' => message, 'success' => success}

  end

  # we'll allow some commands to function normally in the dark
  unchecked_commands = ['go', 'look', 'quit']

  # set command conditions for remaining commands to make sure it's not dark
  @cli.commands.each do |command|
    if !unchecked_commands.index(command.id)
      denial_message = "In the dark? You could easily disturb something!"
      command.condition = "@game.command_check('" + command.id + "', prop, @player, @locations, \"" + denial_message + "\")"
   end
  end

  # start game by issueing "look" command
  @cli.issue_command('look', false)
