---
syntax:
- "build <thing>"

logic: |

  prop = arg['thing']

  output = ''

  if @props[prop]

    if @props[prop].traits['build_with']

      if @player.can_build(prop)

        @player.build(prop)

        output << @game.event(@props[prop], 'on_build')

        @props[prop].location = @player.location

      else

        output << "Something is missing!\n"

      end

    else

      output << "You can't do that.\n"

    end

  else

    output << "I don't see that here.\n"

  end

  output
