---
title: Pirate Adventure Knockoff
width: 600
height: 600
image_height: 200
resizable: true
startup_message: "Welcome to Pirate Adventure Knockoff.\nThis is a port of the 1978 classic by Scott Adams.\n\n"

startup_logic: |

  # set background color
  background '#e3e09f'..'#f6ffd0'

  # monkey patch the CLI output method to change the font style
  def @cli.output(output_text, input_text = '')

    # display output text, emphasize any messages, and show prompt
    @output_stack.clear {
      @output_stack.para \
        output_text,
        @output_stack.em(@message_text, :stroke => '#f00'),
        @output_stack.em(input_text, :fill => '#e3e09f'),
        :font => 'Verdana 14px',
        :stroke => '#120E03',
        :margin_left => 10,
        :margin_right => 10
    }
    @output_stack.scroll_top = @output_stack.scroll_max

  end

  # reset paces
  @game.state['paces'] = 0

  # command conditions execute before commands, so we can use one as a
  # hack to reset paces when player changes location
  def (@game.helpers).go_condition(game)

    game.state['paces'] = 0

    {'success' => true}
  end

  @cli.commands['go'].condition = "@game.helpers.go_condition(@game)"

  # start game by issueing "look" command
  @cli.initial_command('look')
