---
title: New Game
width: 600
height: 600
image_height: 200
resizable: true
startup_message: "Welcome to Some New Game.\n\n"
startup_logic: |
  # start game by issueing "look" command
  @cli.initial_command('look')
